//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "hostmgr", table_name = "hosts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub hostname: String,
    pub fqdn: Option<String>,
    pub physical: Option<bool>,
    pub status: Option<String>,
    pub os_name: Option<String>,
    pub os_version: Option<String>,
    pub os_major: Option<String>,
    pub kernel_version: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"inet\")", select_as = "text", nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"cidr\")", select_as = "text", nullable)]
    pub subnet: Option<String>,
    pub environment: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::disks::Entity")]
    Disks,
    #[sea_orm(has_many = "super::groups::Entity")]
    Groups,
    #[sea_orm(has_many = "super::mounts::Entity")]
    Mounts,
    #[sea_orm(has_many = "super::netlinks::Entity")]
    Netlinks,
    #[sea_orm(has_many = "super::packages::Entity")]
    Packages,
    #[sea_orm(has_many = "super::services::Entity")]
    Services,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::disks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Disks.def()
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl Related<super::mounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mounts.def()
    }
}

impl Related<super::netlinks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Netlinks.def()
    }
}

impl Related<super::packages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Packages.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
