//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "hostmgr", table_name = "netlinks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "netlinks_host_id_interface_name_key")]
    pub host_id: i32,
    #[sea_orm(unique_key = "netlinks_host_id_interface_name_key")]
    pub interface_name: String,
    #[sea_orm(ignore, column_type = "custom(\"inet\")", select_as = "text", nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"macaddr\")",
        select_as = "text",
        nullable
    )]
    pub mac_address: Option<String>,
    pub status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hosts::Entity",
        from = "Column::HostId",
        to = "super::hosts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hosts,
}

impl Related<super::hosts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hosts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
