//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "hostmgr", table_name = "services")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "services_host_id_service_name_key")]
    pub host_id: i32,
    #[sea_orm(unique_key = "services_host_id_service_name_key")]
    pub service_name: String,
    pub status: Option<String>,
    pub enabled: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hosts::Entity",
        from = "Column::HostId",
        to = "super::hosts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hosts,
}

impl Related<super::hosts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hosts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
